version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
    # Uncomment if you want Docker CLI in the backend container
    # privileged: true
    # entrypoint: ["/bin/sh", "-c", "apk add --no-cache docker-cli && npm start"]

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:3000/analyze
